from setuptools import setup

setup(
    name='Subject Cross Validation in Human Activity Recognition',
    version='',
    packages=['lib.python3.6.site-packages.pytz', 'lib.python3.6.site-packages.numpy',
              'lib.python3.6.site-packages.numpy.ma', 'lib.python3.6.site-packages.numpy.ma.tests',
              'lib.python3.6.site-packages.numpy.doc', 'lib.python3.6.site-packages.numpy.fft',
              'lib.python3.6.site-packages.numpy.fft.tests', 'lib.python3.6.site-packages.numpy.lib',
              'lib.python3.6.site-packages.numpy.lib.tests', 'lib.python3.6.site-packages.numpy.core',
              'lib.python3.6.site-packages.numpy.core.tests', 'lib.python3.6.site-packages.numpy.f2py',
              'lib.python3.6.site-packages.numpy.f2py.tests', 'lib.python3.6.site-packages.numpy.tests',
              'lib.python3.6.site-packages.numpy.compat', 'lib.python3.6.site-packages.numpy.compat.tests',
              'lib.python3.6.site-packages.numpy.linalg', 'lib.python3.6.site-packages.numpy.linalg.tests',
              'lib.python3.6.site-packages.numpy.random', 'lib.python3.6.site-packages.numpy.random.tests',
              'lib.python3.6.site-packages.numpy.testing', 'lib.python3.6.site-packages.numpy.testing.tests',
              'lib.python3.6.site-packages.numpy.testing._private', 'lib.python3.6.site-packages.numpy.distutils',
              'lib.python3.6.site-packages.numpy.distutils.tests',
              'lib.python3.6.site-packages.numpy.distutils.command',
              'lib.python3.6.site-packages.numpy.distutils.fcompiler', 'lib.python3.6.site-packages.numpy.matrixlib',
              'lib.python3.6.site-packages.numpy.matrixlib.tests', 'lib.python3.6.site-packages.numpy.polynomial',
              'lib.python3.6.site-packages.numpy.polynomial.tests', 'lib.python3.6.site-packages.scipy',
              'lib.python3.6.site-packages.scipy.io', 'lib.python3.6.site-packages.scipy.io.arff',
              'lib.python3.6.site-packages.scipy.io.arff.tests', 'lib.python3.6.site-packages.scipy.io.tests',
              'lib.python3.6.site-packages.scipy.io.matlab', 'lib.python3.6.site-packages.scipy.io.matlab.tests',
              'lib.python3.6.site-packages.scipy.io.harwell_boeing',
              'lib.python3.6.site-packages.scipy.io.harwell_boeing.tests', 'lib.python3.6.site-packages.scipy.odr',
              'lib.python3.6.site-packages.scipy.odr.tests', 'lib.python3.6.site-packages.scipy._lib',
              'lib.python3.6.site-packages.scipy._lib.tests', 'lib.python3.6.site-packages.scipy.misc',
              'lib.python3.6.site-packages.scipy.misc.tests', 'lib.python3.6.site-packages.scipy.stats',
              'lib.python3.6.site-packages.scipy.stats.tests', 'lib.python3.6.site-packages.scipy.linalg',
              'lib.python3.6.site-packages.scipy.linalg.tests', 'lib.python3.6.site-packages.scipy.signal',
              'lib.python3.6.site-packages.scipy.signal.tests', 'lib.python3.6.site-packages.scipy.signal.windows',
              'lib.python3.6.site-packages.scipy.sparse', 'lib.python3.6.site-packages.scipy.sparse.tests',
              'lib.python3.6.site-packages.scipy.sparse.linalg',
              'lib.python3.6.site-packages.scipy.sparse.linalg.eigen',
              'lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack',
              'lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'lib.python3.6.site-packages.scipy.sparse.linalg.tests',
              'lib.python3.6.site-packages.scipy.sparse.linalg.dsolve',
              'lib.python3.6.site-packages.scipy.sparse.linalg.dsolve.tests',
              'lib.python3.6.site-packages.scipy.sparse.linalg.isolve',
              'lib.python3.6.site-packages.scipy.sparse.linalg.isolve.tests',
              'lib.python3.6.site-packages.scipy.sparse.csgraph',
              'lib.python3.6.site-packages.scipy.sparse.csgraph.tests', 'lib.python3.6.site-packages.scipy.cluster',
              'lib.python3.6.site-packages.scipy.cluster.tests', 'lib.python3.6.site-packages.scipy.fftpack',
              'lib.python3.6.site-packages.scipy.fftpack.tests', 'lib.python3.6.site-packages.scipy.ndimage',
              'lib.python3.6.site-packages.scipy.ndimage.tests', 'lib.python3.6.site-packages.scipy.spatial',
              'lib.python3.6.site-packages.scipy.spatial.tests', 'lib.python3.6.site-packages.scipy.spatial.transform',
              'lib.python3.6.site-packages.scipy.spatial.transform.tests', 'lib.python3.6.site-packages.scipy.special',
              'lib.python3.6.site-packages.scipy.special.tests',
              'lib.python3.6.site-packages.scipy.special._precompute', 'lib.python3.6.site-packages.scipy.optimize',
              'lib.python3.6.site-packages.scipy.optimize._lsq', 'lib.python3.6.site-packages.scipy.optimize.tests',
              'lib.python3.6.site-packages.scipy.optimize._trlib',
              'lib.python3.6.site-packages.scipy.optimize._shgo_lib',
              'lib.python3.6.site-packages.scipy.optimize._trustregion_constr',
              'lib.python3.6.site-packages.scipy.optimize._trustregion_constr.tests',
              'lib.python3.6.site-packages.scipy.constants', 'lib.python3.6.site-packages.scipy.constants.tests',
              'lib.python3.6.site-packages.scipy.integrate', 'lib.python3.6.site-packages.scipy.integrate._ivp',
              'lib.python3.6.site-packages.scipy.integrate.tests', 'lib.python3.6.site-packages.scipy.interpolate',
              'lib.python3.6.site-packages.scipy.interpolate.tests', 'lib.python3.6.site-packages.scipy._build_utils',
              'lib.python3.6.site-packages.pandas', 'lib.python3.6.site-packages.pandas.io',
              'lib.python3.6.site-packages.pandas.io.sas', 'lib.python3.6.site-packages.pandas.io.json',
              'lib.python3.6.site-packages.pandas.io.formats', 'lib.python3.6.site-packages.pandas.io.msgpack',
              'lib.python3.6.site-packages.pandas.io.clipboard', 'lib.python3.6.site-packages.pandas.api',
              'lib.python3.6.site-packages.pandas.api.types', 'lib.python3.6.site-packages.pandas.api.extensions',
              'lib.python3.6.site-packages.pandas.core', 'lib.python3.6.site-packages.pandas.core.util',
              'lib.python3.6.site-packages.pandas.core.tools', 'lib.python3.6.site-packages.pandas.core.arrays',
              'lib.python3.6.site-packages.pandas.core.dtypes', 'lib.python3.6.site-packages.pandas.core.sparse',
              'lib.python3.6.site-packages.pandas.core.groupby', 'lib.python3.6.site-packages.pandas.core.indexes',
              'lib.python3.6.site-packages.pandas.core.reshape', 'lib.python3.6.site-packages.pandas.core.internals',
              'lib.python3.6.site-packages.pandas.core.computation', 'lib.python3.6.site-packages.pandas.util',
              'lib.python3.6.site-packages.pandas._libs', 'lib.python3.6.site-packages.pandas._libs.tslibs',
              'lib.python3.6.site-packages.pandas.tests', 'lib.python3.6.site-packages.pandas.tests.io',
              'lib.python3.6.site-packages.pandas.tests.io.sas', 'lib.python3.6.site-packages.pandas.tests.io.json',
              'lib.python3.6.site-packages.pandas.tests.io.parser',
              'lib.python3.6.site-packages.pandas.tests.io.formats',
              'lib.python3.6.site-packages.pandas.tests.io.msgpack', 'lib.python3.6.site-packages.pandas.tests.api',
              'lib.python3.6.site-packages.pandas.tests.util', 'lib.python3.6.site-packages.pandas.tests.frame',
              'lib.python3.6.site-packages.pandas.tests.tools', 'lib.python3.6.site-packages.pandas.tests.arrays',
              'lib.python3.6.site-packages.pandas.tests.arrays.sparse',
              'lib.python3.6.site-packages.pandas.tests.arrays.interval',
              'lib.python3.6.site-packages.pandas.tests.arrays.categorical',
              'lib.python3.6.site-packages.pandas.tests.dtypes', 'lib.python3.6.site-packages.pandas.tests.dtypes.cast',
              'lib.python3.6.site-packages.pandas.tests.scalar',
              'lib.python3.6.site-packages.pandas.tests.scalar.period',
              'lib.python3.6.site-packages.pandas.tests.scalar.interval',
              'lib.python3.6.site-packages.pandas.tests.scalar.timedelta',
              'lib.python3.6.site-packages.pandas.tests.scalar.timestamp',
              'lib.python3.6.site-packages.pandas.tests.series',
              'lib.python3.6.site-packages.pandas.tests.series.indexing',
              'lib.python3.6.site-packages.pandas.tests.sparse',
              'lib.python3.6.site-packages.pandas.tests.sparse.frame',
              'lib.python3.6.site-packages.pandas.tests.sparse.series',
              'lib.python3.6.site-packages.pandas.tests.tslibs', 'lib.python3.6.site-packages.pandas.tests.generic',
              'lib.python3.6.site-packages.pandas.tests.groupby',
              'lib.python3.6.site-packages.pandas.tests.groupby.aggregate',
              'lib.python3.6.site-packages.pandas.tests.indexes',
              'lib.python3.6.site-packages.pandas.tests.indexes.multi',
              'lib.python3.6.site-packages.pandas.tests.indexes.period',
              'lib.python3.6.site-packages.pandas.tests.indexes.interval',
              'lib.python3.6.site-packages.pandas.tests.indexes.datetimes',
              'lib.python3.6.site-packages.pandas.tests.indexes.timedeltas',
              'lib.python3.6.site-packages.pandas.tests.reshape',
              'lib.python3.6.site-packages.pandas.tests.reshape.merge',
              'lib.python3.6.site-packages.pandas.tests.tseries',
              'lib.python3.6.site-packages.pandas.tests.tseries.offsets',
              'lib.python3.6.site-packages.pandas.tests.indexing',
              'lib.python3.6.site-packages.pandas.tests.indexing.interval',
              'lib.python3.6.site-packages.pandas.tests.indexing.multiindex',
              'lib.python3.6.site-packages.pandas.tests.plotting', 'lib.python3.6.site-packages.pandas.tests.resample',
              'lib.python3.6.site-packages.pandas.tests.extension',
              'lib.python3.6.site-packages.pandas.tests.extension.base',
              'lib.python3.6.site-packages.pandas.tests.extension.json',
              'lib.python3.6.site-packages.pandas.tests.extension.arrow',
              'lib.python3.6.site-packages.pandas.tests.extension.numpy_',
              'lib.python3.6.site-packages.pandas.tests.extension.decimal',
              'lib.python3.6.site-packages.pandas.tests.internals',
              'lib.python3.6.site-packages.pandas.tests.arithmetic',
              'lib.python3.6.site-packages.pandas.tests.reductions',
              'lib.python3.6.site-packages.pandas.tests.computation', 'lib.python3.6.site-packages.pandas.arrays',
              'lib.python3.6.site-packages.pandas.compat', 'lib.python3.6.site-packages.pandas.compat.numpy',
              'lib.python3.6.site-packages.pandas.errors', 'lib.python3.6.site-packages.pandas.tseries',
              'lib.python3.6.site-packages.pandas.plotting', 'lib.python3.6.site-packages.sklearn',
              'lib.python3.6.site-packages.sklearn.svm', 'lib.python3.6.site-packages.sklearn.svm.tests',
              'lib.python3.6.site-packages.sklearn.tree', 'lib.python3.6.site-packages.sklearn.tree.tests',
              'lib.python3.6.site-packages.sklearn.tests', 'lib.python3.6.site-packages.sklearn.utils',
              'lib.python3.6.site-packages.sklearn.utils.tests',
              'lib.python3.6.site-packages.sklearn.utils.sparsetools',
              'lib.python3.6.site-packages.sklearn.utils.sparsetools.tests',
              'lib.python3.6.site-packages.sklearn.cluster', 'lib.python3.6.site-packages.sklearn.cluster.tests',
              'lib.python3.6.site-packages.sklearn.compose', 'lib.python3.6.site-packages.sklearn.compose.tests',
              'lib.python3.6.site-packages.sklearn.metrics', 'lib.python3.6.site-packages.sklearn.metrics.tests',
              'lib.python3.6.site-packages.sklearn.metrics.cluster',
              'lib.python3.6.site-packages.sklearn.metrics.cluster.tests',
              'lib.python3.6.site-packages.sklearn.mixture', 'lib.python3.6.site-packages.sklearn.mixture.tests',
              'lib.python3.6.site-packages.sklearn.datasets', 'lib.python3.6.site-packages.sklearn.datasets.tests',
              'lib.python3.6.site-packages.sklearn.ensemble', 'lib.python3.6.site-packages.sklearn.ensemble.tests',
              'lib.python3.6.site-packages.sklearn.manifold', 'lib.python3.6.site-packages.sklearn.manifold.tests',
              'lib.python3.6.site-packages.sklearn.externals', 'lib.python3.6.site-packages.sklearn.externals.joblib',
              'lib.python3.6.site-packages.sklearn.externals.joblib.externals',
              'lib.python3.6.site-packages.sklearn.externals.joblib.externals.loky',
              'lib.python3.6.site-packages.sklearn.externals.joblib.externals.loky.backend',
              'lib.python3.6.site-packages.sklearn.externals.joblib.externals.cloudpickle',
              'lib.python3.6.site-packages.sklearn.neighbors', 'lib.python3.6.site-packages.sklearn.neighbors.tests',
              'lib.python3.6.site-packages.sklearn.covariance', 'lib.python3.6.site-packages.sklearn.covariance.tests',
              'lib.python3.6.site-packages.sklearn._build_utils', 'lib.python3.6.site-packages.sklearn.linear_model',
              'lib.python3.6.site-packages.sklearn.linear_model.tests',
              'lib.python3.6.site-packages.sklearn.__check_build', 'lib.python3.6.site-packages.sklearn.decomposition',
              'lib.python3.6.site-packages.sklearn.decomposition.tests',
              'lib.python3.6.site-packages.sklearn.preprocessing',
              'lib.python3.6.site-packages.sklearn.preprocessing.tests',
              'lib.python3.6.site-packages.sklearn.neural_network',
              'lib.python3.6.site-packages.sklearn.neural_network.tests',
              'lib.python3.6.site-packages.sklearn.model_selection',
              'lib.python3.6.site-packages.sklearn.model_selection.tests',
              'lib.python3.6.site-packages.sklearn.semi_supervised',
              'lib.python3.6.site-packages.sklearn.semi_supervised.tests',
              'lib.python3.6.site-packages.sklearn.gaussian_process',
              'lib.python3.6.site-packages.sklearn.gaussian_process.tests',
              'lib.python3.6.site-packages.sklearn.feature_selection',
              'lib.python3.6.site-packages.sklearn.feature_selection.tests',
              'lib.python3.6.site-packages.sklearn.feature_extraction',
              'lib.python3.6.site-packages.sklearn.feature_extraction.tests',
              'lib.python3.6.site-packages.sklearn.cross_decomposition',
              'lib.python3.6.site-packages.sklearn.cross_decomposition.tests', 'lib.python3.6.site-packages.dateutil',
              'lib.python3.6.site-packages.dateutil.tz', 'lib.python3.6.site-packages.dateutil.parser',
              'lib.python3.6.site-packages.dateutil.zoneinfo', 'lib.python3.6.site-packages.matplotlib',
              'lib.python3.6.site-packages.matplotlib.tri', 'lib.python3.6.site-packages.matplotlib.axes',
              'lib.python3.6.site-packages.matplotlib.cbook', 'lib.python3.6.site-packages.matplotlib.style',
              'lib.python3.6.site-packages.matplotlib.tests', 'lib.python3.6.site-packages.matplotlib.compat',
              'lib.python3.6.site-packages.matplotlib.testing',
              'lib.python3.6.site-packages.matplotlib.testing.jpl_units',
              'lib.python3.6.site-packages.matplotlib.backends',
              'lib.python3.6.site-packages.matplotlib.backends.qt_editor',
              'lib.python3.6.site-packages.matplotlib.sphinxext',
              'lib.python3.6.site-packages.matplotlib.sphinxext.tests',
              'lib.python3.6.site-packages.matplotlib.projections', 'lib.python3.6.site-packages.mpl_toolkits.tests',
              'lib.python3.6.site-packages.mpl_toolkits.mplot3d', 'lib.python3.6.site-packages.mpl_toolkits.axes_grid',
              'lib.python3.6.site-packages.mpl_toolkits.axes_grid1',
              'lib.python3.6.site-packages.mpl_toolkits.axisartist',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'lib64.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations'],
    url='',
    license='',
    author='',
    author_email='',
    description=''
)
